#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sun Jan 24 18:00:20 2021
#

import wx
import wx.adv
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from .keychoice import KeyChoice
from .batch import BatchValidator
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1129, 703))
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY)
        self.vaccinators = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.vaccinator_data = wx.grid.Grid(self.vaccinators, wx.ID_ANY, size=(1, 1))
        self.button_8 = wx.Button(self.vaccinators, wx.ID_ANY, "Confirm vaccinators")
        self.make_forms = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.imported_data_list = wx.ListCtrl(self.make_forms, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.imported_count_label = wx.StaticText(self.make_forms, wx.ID_ANY, "0")
        self.button_1 = wx.Button(self.make_forms, wx.ID_ANY, "Import Appointments")
        self.button_2 = wx.Button(self.make_forms, wx.ID_ANY, "Clear Data")
        self.button_3 = wx.Button(self.make_forms, wx.ID_ANY, "Create Forms")
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.scanned_data_list = wx.ListCtrl(self.notebook_1_pane_3, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.scanned_count_label = wx.StaticText(self.notebook_1_pane_3, wx.ID_ANY, "0")
        self.button_4 = wx.Button(self.notebook_1_pane_3, wx.ID_ANY, "Read Scanned Forms")
        self.button_5 = wx.Button(self.notebook_1_pane_3, wx.ID_ANY, "Clear Data")
        self.button_6 = wx.Button(self.notebook_1_pane_3, wx.ID_ANY, "Upload to Pinnacle")
        self.notebook_1_Checkin = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.check_in_search = wx.SearchCtrl(self.notebook_1_Checkin, wx.ID_ANY, "")
        self.check_in_search.Bind(wx.EVT_KEY_DOWN, self.check_in_search_activity)
        self.check_in_vaccinator = KeyChoice(self.notebook_1_Checkin, wx.ID_ANY, choices=["---"])
        self.check_in_drawer = KeyChoice(self.notebook_1_Checkin, wx.ID_ANY, choices=["Vaccinator"])
        self.check_in_batch = wx.Choice(self.notebook_1_Checkin, wx.ID_ANY, choices=["---"])
        self.button_12 = wx.Button(self.notebook_1_Checkin, wx.ID_ANY, "Upload")
        self.check_in_data_list = wx.ListCtrl(self.notebook_1_Checkin, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.button_13 = wx.Button(self.notebook_1_Checkin, wx.ID_ANY, "Manage Batches")
        self.notebook_1_pane_4 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.completed_data_list = wx.ListCtrl(self.notebook_1_pane_4, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.completed_count_label = wx.StaticText(self.notebook_1_pane_4, wx.ID_ANY, "0")
        self.button_10 = wx.Button(self.notebook_1_pane_4, wx.ID_ANY, "Print Summary")
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.error_data_list = wx.ListCtrl(self.notebook_1_pane_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.error_count_label = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "0")
        self.button_7 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "Print Errors")
        self.notebook_1_Logs = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.log_info = wx.TextCtrl(self.notebook_1_Logs, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_RICH)
        self.notebook_1_About = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.hyperlink_1 = wx.adv.HyperlinkCtrl(self.notebook_1_About, wx.ID_ANY, "Website: http://github.com/furbrain/climber", "http://github.com/furbrain/climber", style=wx.adv.HL_ALIGN_CENTRE)
        self.button_9 = wx.Button(self.notebook_1_About, wx.ID_HELP, "")
        self.button_11 = wx.Button(self.notebook_1_About, wx.ID_ANY, "Self test")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.check_vaccinators, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.import_session, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.clear_data, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.create_forms, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.load_scanned_forms, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.clear_data, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.upload_data, self.button_6)
        self.Bind(wx.EVT_TEXT, self.check_in_search_activity, self.check_in_search)
        self.Bind(wx.EVT_BUTTON, self.check_in_upload_clicked, self.button_12)
        self.Bind(wx.EVT_BUTTON, self.manage_batches_clicked, self.button_13)
        self.Bind(wx.EVT_BUTTON, self.create_summary, self.button_10)
        self.Bind(wx.EVT_BUTTON, self.print_errors, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.show_help, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.self_test, self.button_11)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.page_changed, self.notebook_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Covid Climber")
        self.vaccinator_data.CreateGrid(7, 2)
        self.vaccinator_data.SetColLabelValue(0, "Initials")
        self.vaccinator_data.SetColSize(0, 100)
        self.vaccinator_data.SetColLabelValue(1, "Name")
        self.vaccinator_data.SetColSize(1, 550)
        self.imported_data_list.AppendColumn("Time", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.imported_data_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.imported_data_list.AppendColumn("Dob", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.imported_data_list.AppendColumn("NHS Number", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.scanned_data_list.AppendColumn("Time", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.scanned_data_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.scanned_data_list.AppendColumn("DoB", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.scanned_data_list.AppendColumn("NHS number", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.scanned_data_list.AppendColumn("Vaccinator", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.check_in_search.SetDescriptiveText("Name")
        self.check_in_vaccinator.SetSelection(0)
        self.check_in_drawer.SetSelection(0)
        self.check_in_batch.SetSelection(0)
        self.button_12.SetDefault()
        self.check_in_data_list.AppendColumn("Time", format=wx.LIST_FORMAT_LEFT, width=100)
        self.check_in_data_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=500)
        self.check_in_data_list.AppendColumn("Dob", format=wx.LIST_FORMAT_LEFT, width=150)
        self.check_in_data_list.AppendColumn("NHS Number", format=wx.LIST_FORMAT_LEFT, width=150)
        self.completed_data_list.AppendColumn("Time", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.completed_data_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.completed_data_list.AppendColumn("Dob", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.completed_data_list.AppendColumn("NHS Number", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("Time", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("Name", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("DoB", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("NHS number", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("Error", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.error_data_list.AppendColumn("Has Image", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.VERTICAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_20 = wx.BoxSizer(wx.VERTICAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        label_2 = wx.StaticText(self.vaccinators, wx.ID_ANY, "Please enter initials and names for all people who may be vaccinating this group", style=wx.ALIGN_LEFT)
        sizer_6.Add(label_2, 0, wx.ALL, 3)
        sizer_6.Add(self.vaccinator_data, 1, wx.ALL | wx.EXPAND, 3)
        sizer_9.Add(self.button_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_6.Add(sizer_9, 0, wx.ALIGN_RIGHT | wx.ALL, 6)
        self.vaccinators.SetSizer(sizer_6)
        sizer_2.Add(self.imported_data_list, 2, wx.ALL | wx.EXPAND, 3)
        label_1 = wx.StaticText(self.make_forms, wx.ID_ANY, "People:")
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_3.Add(self.imported_count_label, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_3.Add(self.button_1, 0, wx.ALL, 3)
        sizer_3.Add(self.button_2, 0, wx.ALL, 3)
        sizer_3.Add(self.button_3, 0, wx.ALL, 3)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        self.make_forms.SetSizer(sizer_2)
        sizer_4.Add(self.scanned_data_list, 1, wx.EXPAND, 0)
        label_4 = wx.StaticText(self.notebook_1_pane_3, wx.ID_ANY, "Scanned People:")
        sizer_5.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_5.Add(self.scanned_count_label, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_5.Add(self.button_4, 0, wx.ALL, 3)
        sizer_5.Add(self.button_5, 0, wx.ALL, 3)
        sizer_5.Add(self.button_6, 0, wx.ALL, 3)
        sizer_4.Add(sizer_5, 0, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetSizer(sizer_4)
        sizer_21.Add(self.check_in_search, 2, wx.ALL | wx.EXPAND, 3)
        sizer_21.Add((20, 5), 0, 0, 0)
        label_12 = wx.StaticText(self.notebook_1_Checkin, wx.ID_ANY, "Vaccinator:", style=wx.ALIGN_RIGHT)
        sizer_21.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add(self.check_in_vaccinator, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add((20, 5), 0, 0, 0)
        label_13 = wx.StaticText(self.notebook_1_Checkin, wx.ID_ANY, "Drawer:", style=wx.ALIGN_RIGHT)
        sizer_21.Add(label_13, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add(self.check_in_drawer, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add((20, 5), 0, 0, 0)
        label_14 = wx.StaticText(self.notebook_1_Checkin, wx.ID_ANY, "Batch:", style=wx.ALIGN_RIGHT)
        sizer_21.Add(label_14, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add(self.check_in_batch, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_21.Add((20, 5), 0, 0, 0)
        sizer_21.Add(self.button_12, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_20.Add(sizer_21, 0, 0, 0)
        sizer_20.Add(self.check_in_data_list, 2, wx.ALL | wx.EXPAND, 3)
        sizer_13.Add(self.button_13, 0, wx.ALL, 3)
        sizer_20.Add(sizer_13, 0, wx.ALIGN_RIGHT, 0)
        self.notebook_1_Checkin.SetSizer(sizer_20)
        sizer_10.Add(self.completed_data_list, 2, wx.ALL | wx.EXPAND, 3)
        label_5 = wx.StaticText(self.notebook_1_pane_4, wx.ID_ANY, "People:")
        sizer_11.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_11.Add(self.completed_count_label, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_11.Add(self.button_10, 0, wx.ALL, 3)
        sizer_10.Add(sizer_11, 0, wx.EXPAND, 0)
        self.notebook_1_pane_4.SetSizer(sizer_10)
        sizer_7.Add(self.error_data_list, 1, wx.EXPAND, 0)
        label_3 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "Error count: ")
        sizer_8.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_8.Add(self.error_count_label, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_8.Add(self.button_7, 0, wx.ALL, 3)
        sizer_7.Add(sizer_8, 0, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_7)
        sizer_19.Add(self.log_info, 1, wx.ALL | wx.EXPAND, 6)
        self.notebook_1_Logs.SetSizer(sizer_19)
        label_9 = wx.StaticText(self.notebook_1_About, wx.ID_ANY, "Climber: covid vaccine batch uploader")
        label_9.SetFont(wx.Font(16, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_17.Add(label_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 3)
        label_10 = wx.StaticText(self.notebook_1_About, wx.ID_ANY, "Copyright 2020 Phil Underwood\n")
        sizer_17.Add(label_10, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 3)
        sizer_17.Add(self.hyperlink_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 3)
        sizer_16.Add(sizer_17, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL | wx.SHAPED, 6)
        sizer_18.Add(self.button_9, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_18.Add(self.button_11, 0, wx.ALL, 3)
        sizer_16.Add(sizer_18, 0, wx.ALIGN_RIGHT | wx.ALL, 6)
        self.notebook_1_About.SetSizer(sizer_16)
        self.notebook_1.AddPage(self.vaccinators, "Vaccinators")
        self.notebook_1.AddPage(self.make_forms, "Create forms")
        self.notebook_1.AddPage(self.notebook_1_pane_3, "Submit Scans")
        self.notebook_1.AddPage(self.notebook_1_Checkin, "Check-in")
        self.notebook_1.AddPage(self.notebook_1_pane_4, "Completed")
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Errors")
        self.notebook_1.AddPage(self.notebook_1_Logs, "Logs")
        self.notebook_1.AddPage(self.notebook_1_About, "About")
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def check_vaccinators(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'check_vaccinators' not implemented!")
        event.Skip()

    def import_session(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'import_session' not implemented!")
        event.Skip()

    def clear_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'clear_data' not implemented!")
        event.Skip()

    def create_forms(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'create_forms' not implemented!")
        event.Skip()

    def load_scanned_forms(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'load_scanned_forms' not implemented!")
        event.Skip()

    def upload_data(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'upload_data' not implemented!")
        event.Skip()

    def check_in_search_activity(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'check_in_search_activity' not implemented!")
        event.Skip()

    def check_in_upload_clicked(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'check_in_upload_clicked' not implemented!")
        event.Skip()

    def manage_batches_clicked(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'manage_batches_clicked' not implemented!")
        event.Skip()

    def create_summary(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'create_summary' not implemented!")
        event.Skip()

    def print_errors(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'print_errors' not implemented!")
        event.Skip()

    def show_help(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'show_help' not implemented!")
        event.Skip()

    def self_test(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'self_test' not implemented!")
        event.Skip()

    def page_changed(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'page_changed' not implemented!")
        event.Skip()

# end of class MyFrame

class GetUploadData(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GetUploadData.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.clinic_date = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.clinic_date.SetValidator(BatchValidator())
        self.drawer_is_vaccinator = wx.RadioButton(self, wx.ID_ANY, "Vaccinator draws up")
        self.drawer_is_specified = wx.RadioButton(self, wx.ID_ANY, "Specific drawer: ")
        self.drawer_name = wx.TextCtrl(self, wx.ID_ANY, "")
        self.manufacturer = wx.Choice(self, wx.ID_ANY, choices=["Pfizer", "AstraZeneca 10 dose", "AstraZeneca 8 dose"])
        self.batch = wx.TextCtrl(self, wx.ID_ANY, "")
        self.use_by_date = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.expiry_date = wx.adv.DatePickerCtrl(self, wx.ID_ANY)
        self.ok_button = wx.Button(self, wx.ID_OK, "")
        self.cancel_button = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_RADIOBUTTON, lambda x: self.drawer_name.Disable(), self.drawer_is_vaccinator)
        self.Bind(wx.EVT_RADIOBUTTON, lambda x: self.drawer_name.Enable(), self.drawer_is_specified)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: GetUploadData.__set_properties
        self.SetTitle("Start upload")
        self.drawer_is_vaccinator.SetValue(1)
        self.drawer_name.SetMinSize((300, -1))
        self.drawer_name.Enable(False)
        self.manufacturer.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: GetUploadData.__do_layout
        self.main_sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Vaccine details"), wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(4, 2, 6, 6)
        self.drawer_section = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Drawer"), wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        self.clinic_date_section = wx.BoxSizer(wx.HORIZONTAL)
        label_8 = wx.StaticText(self, wx.ID_ANY, "Clinic Date: ", style=wx.ALIGN_RIGHT)
        self.clinic_date_section.Add(label_8, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        self.clinic_date_section.Add(self.clinic_date, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        self.main_sizer.Add(self.clinic_date_section, 0, wx.ALL | wx.EXPAND, 6)
        self.drawer_section.Add(self.drawer_is_vaccinator, 0, wx.ALL, 3)
        sizer_14.Add(self.drawer_is_specified, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 3)
        sizer_14.Add(self.drawer_name, 1, wx.ALL | wx.EXPAND, 3)
        self.drawer_section.Add(sizer_14, 1, wx.EXPAND, 0)
        self.main_sizer.Add(self.drawer_section, 0, wx.ALL | wx.EXPAND, 6)
        label_5 = wx.StaticText(self, wx.ID_ANY, "Manufacturer: ", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.manufacturer, 0, 0, 0)
        label_6 = wx.StaticText(self, wx.ID_ANY, "Batch: ", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.batch, 0, wx.EXPAND, 0)
        label_7 = wx.StaticText(self, wx.ID_ANY, "Use by: ", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.use_by_date, 0, 0, 0)
        Expires = wx.StaticText(self, wx.ID_ANY, "Expires: ", style=wx.ALIGN_RIGHT)
        grid_sizer_1.Add(Expires, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)
        grid_sizer_1.Add(self.expiry_date, 0, 0, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_12.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 3)
        self.main_sizer.Add(sizer_12, 0, wx.ALL | wx.EXPAND, 6)
        sizer_11.Add(self.ok_button, 0, wx.ALL, 3)
        sizer_11.Add(self.cancel_button, 0, wx.ALL, 3)
        self.main_sizer.Add(sizer_11, 0, wx.ALIGN_RIGHT | wx.ALL, 6)
        self.SetSizer(self.main_sizer)
        self.main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

# end of class GetUploadData

class BatchDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BatchDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.batch_list_ctrl = wx.ListCtrl(self, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_VRULES)
        self.button_14 = wx.Button(self, wx.ID_ADD, "")
        self.button_15 = wx.Button(self, wx.ID_ANY, "Edit")
        self.button_16 = wx.Button(self, wx.ID_DELETE, "")
        self.button_17 = wx.Button(self, wx.ID_OK, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.add_batch, self.button_14)
        self.Bind(wx.EVT_BUTTON, self.edit_batch, self.button_15)
        self.Bind(wx.EVT_BUTTON, self.delete_batch, self.button_16)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BatchDialog.__set_properties
        self.SetTitle("Batch Manager")
        self.batch_list_ctrl.AppendColumn("Bacth Number", format=wx.LIST_FORMAT_LEFT, width=150)
        self.batch_list_ctrl.AppendColumn("Type", format=wx.LIST_FORMAT_LEFT, width=300)
        self.batch_list_ctrl.AppendColumn("Use By", format=wx.LIST_FORMAT_LEFT, width=150)
        self.batch_list_ctrl.AppendColumn("Expires", format=wx.LIST_FORMAT_LEFT, width=150)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BatchDialog.__do_layout
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_22.Add(self.batch_list_ctrl, 1, wx.EXPAND, 0)
        sizer_23.Add(self.button_14, 0, wx.ALL, 3)
        sizer_23.Add(self.button_15, 0, wx.ALL, 3)
        sizer_23.Add(self.button_16, 0, wx.ALL, 3)
        sizer_23.Add(self.button_17, 0, wx.ALL, 3)
        sizer_22.Add(sizer_23, 0, wx.ALIGN_RIGHT | wx.ALL, 3)
        self.SetSizer(sizer_22)
        sizer_22.Fit(self)
        self.Layout()
        # end wxGlade

    def add_batch(self, event):  # wxGlade: BatchDialog.<event_handler>
        print("Event handler 'add_batch' not implemented!")
        event.Skip()

    def edit_batch(self, event):  # wxGlade: BatchDialog.<event_handler>
        print("Event handler 'edit_batch' not implemented!")
        event.Skip()

    def delete_batch(self, event):  # wxGlade: BatchDialog.<event_handler>
        print("Event handler 'delete_batch' not implemented!")
        event.Skip()

# end of class BatchDialog

class MyApp(wx.App):
    def OnInit(self):
        self.Climber = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.Climber)
        self.Climber.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
